### ISSUE TITLE
Error, not found!

### ISSUE THREAD

**Issue by Acanterelle** [rosshamish/docker-deep-dream-video#2]
Hi, I tired pulling the repo through docker after succesfully running docker run hello-world and got:

...
bash-3.2$ docker pull rosshamish/deep-dream-generator-video
Pulling repository rosshamish/deep-dream-generator-video
Error: image rosshamish/deep-dream-generator-video:latest not found
bash-3.2$ 

OSX 10.10.2
Boot2docker

**Comment by rosshamish** [comment]
The image is failing to build right now - I'll update the README to reflect that until I get around to finishing/fixing it. Thanks for the heads up!
